osx_image: xcode11.6
language: objective-c
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
notifications:
  email:
    - jam330257@gmail.com

# Ensure that fastlane is at the latest version
before_install:
- brew update
- bundle install

jobs:
  include:
    - stage: test
      script: 
        - fastlane scan